name: Trivy Full Security Scan

on:
  push:
    branches:
      - master  # hoặc 'main' tùy repo

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run Trivy
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          scan-ref: '.'
          format: table
          exit-code: '0'
